#!/usr/bin/env python

"""
git commit message hook script.

Put me at /your/git/repo/.git/hooks/commit-msg
"""

import re
import sys

def log(message=""):
    sys.stdout.write("%s\n" % message)

def bubble(msg):
    altered_msg = u"| %s! |" % msg
    log()
    log(u"_" * len(altered_msg))
    log(altered_msg)
    log(u"-" * len(altered_msg))

def fail(msg):
    bubble(msg)
    log(u"    /")
    log(u"\u0028\u256f\u00b0\u25a1\u00b0\u0029\u256f\ufe35 \u253b\u2501\u253b")
    log()
    sys.exit(1)

def ok(msg):
    bubble(msg)
    log(u"     /")
    log(u"\u0028\u30d8\uff65\u005f\uff65\u0029\u30d8\u252c\u2500\u2500\u252c")
    log()

def main():
    if len(sys.argv) != 2:
        fail("no file specified")

    with open(sys.argv[1], "r") as message_file:
        title = message_file.readline()
        words = title.split(" ")
        if len(words) < 2 or len(words[1]) == 0:
            fail("not enough words in commit message")

        if words[0] == "[build]":
            pass
        elif words[0] == "[wip]":
            pass
        elif words[0] == "[internal]":
            pass
        elif words[0] == "[feature]":
            pass
        elif words[0] == "[bug]":
            if re.match("#[1-9][0-9]*:", words[1]) == None:
                fail("invalid bug number")
            if len(words) < 3 or len(words[2]) == 0:
                fail("no bug description")
        elif words[0] == "Merge":
            pass
        elif words[0] == "Revert":
            pass
        else:
            fail("invalid tag")

        ok("nice commit message")

if __name__ == "__main__":
    main()
