#!/usr/bin/env python

"""
git commit message hook script.

Put me at /your/git/repo/.git/hooks/commit-msg
"""

import re
import sys

def fail(msg):
    altered_msg = u"| %s! |" % msg
    print
    print u"_" * len(altered_msg)
    print altered_msg
    print u"-" * len(altered_msg)
    print u"    /"
    print u"\u0028\u256f\u00b0\u25a1\u00b0\u0029\u256f\ufe35 \u253b\u2501\u253b"
    print
    sys.exit(1)

def main():
    if len(sys.argv) != 2:
        fail("no file specified")

    with open(sys.argv[1], "r") as message_file:
        title = message_file.readline()
        words = title.split(" ")
        if len(words) < 2 or len(words[1]) == 0:
            fail("not enough words in commit message")

        if words[0] == "[build]":
            pass
        elif words[0] == "[wip]":
            pass
        elif words[0] == "[internal]":
            pass
        elif words[0] == "[feature]":
            pass
        elif words[0] == "[bug]":
            if re.match("#[1-9][0-9]*:", words[1]) == None:
                fail("invalid bug number")
            if len(words) < 3 or len(words[2]) == 0:
                fail("no bug description")
        else:
            fail("invalid tag")

if __name__ == "__main__":
    main()
